### ISSUE TITLE
关于环境的一些问题

### ISSUE THREAD

**Issue by XieXiLin3** [kenvix/moecraft-updater#9]
在我刚 Clone 下来之后，我等待 IDEA 自动补全文件，编译会报下图的错。
![](https://user-images.githubusercontent.com/55585872/208249693-c654c871-78f3-4754-b706-2426cfe2d556.png)
在编译文件成功出现后，我尝试双击 / 命令提示符运行 此文件，会报缺少组件。
![](https://user-images.githubusercontent.com/55585872/208249346-fa86179f-5c6b-4a15-9ecd-83f6c978aedd.png)
请问是否有什么文件需要另外下载的，或者有什么附言，谢谢。

**Comment by kenvix** [comment]
安装带FX的JRE或通过Gradle配置JavaFX
